version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: admin-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
      - CHOKIDAR_USEPOLLING=true 
    restart: "no"
